spring:
  application:
    name: api-gateway-service
server:
  port: 9003

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.12.222:9000/eureka/
  instance:
    prefer-ip-address: true